### ISSUE TITLE
A potential bug with CNF Examples while using sharpSAT

### ISSUE THREAD

**Issue by Annlean** [marcthurley/sharpSAT#16]
Hi!

I would like to express my appreciation and gratitude for your excellent work in developing sharpSAT. 

However, I recently encountered an issue while utilizing sharpSAT. I attempted to process two CNF files using sharpSAT. I set the timeout of running the model counter to 600 seconds. 

The **origin.cnf** file is satisfiable, and the counting result should be a positive integer. The **new.cnf** file is an unsatisfiable CNF file, which is generated by updating the **origin.cnf** file, and its counting result should be 0. But for **new.cnf**, the counting result from sharpSAT is not 0, indicating that sharpSAT incorrectly generated a satisfiable counting result.

I think sharpSAT may have a potential bug, and I hope this information can assist you to address the potential bugs. The two example files are attached [here](https://drive.google.com/drive/folders/1lT226XklMd-Z1dlNRaayRdxhw_AhL9k-?usp=sharing) for your reference.

Looking forward to your response. If you need any additional information or test data, please feel free to let me know. Thank you for your time and effort in developing this valuable tool.

Best regards,

Haiyan and Jifeng
CSTAR group

**Comment by ZaydH** [comment]
Note: I am not the owner or maintainer of SharpSAT.

Unfortunately, sharpSAT has not been maintained for a while, and some known issues have not been fixed for a few years.  Although I hope I am wrong, I wouldn't expect a fix here.

FWIW, I forked sharpSAT several years ago to support work on another paper.  Our tool, [https://github.com/ZaydH/spur](SPUR) still supports the original counting functionality along with new sampling functionality.

I ran your two formulas through my updated version of sharpSAT and confirm that `origin.cnf` has two solutions and that `new.cnf` is unsat.  

Here is a log from running your formula in SPUR with counting only enabled:

```
~/repos/spur master*
❯ ./build/Release/spur -cnf ~/repos/spur/new.cnf -count-only


variables (total / active / free)	0/0/0
clauses (removed) 		0 (18446744073709551549)
decisions 				0
conflicts 				0
conflict clauses (all/bin/unit) 	0/0/67
failed literals found by implicit BCP 	 0
implicit BCP miss rate 	0%
bytes cache size     	104
bytes cache (overall) 	104
bytes cache (infra / comps) 104/0
bytes pure comp data (curr)    0
bytes pure comp data (overall) 0
bytes cache with sysoverh (curr)    0
bytes cache with sysoverh (overall) 0
cache (stores / hits) 			0/0
cache miss rate 		0%
avg. variable count (stores / hits) 	nan/0


# solutions
0

# END

time: 0.000608s
```

If you have any questions, let me know.

**Comment by Annlean** [comment]
Thanks for your reply!
I will try using SPUR. If there are any issues related to SPUR, I will tell you. Thanks again!
